#!/usr/bin/env bash

set -e
set -x

local_copy_name="$1" 

original_file=$([[ -f .env ]] && grep "ORIGINAL_FILE" .env | cut -d "=" -f 2)
[[ -f "${original_file}" ]] 


awk '/^#/{found=1} found' "${original_file}" > "${local_copy_name}" 

echo "${original_file}" copied to "${local_copy_name}"
